apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bankapp-ingress
  namespace: bankapp-namespace
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - megaproject.divyaknair.com
    secretName: bankapp-tls

 
  rules:
  - host: megaproject.divyaknair.com
    http:
      paths:      
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: bankapp-service
            port:
              number: 8080
      - path: /nginx
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80      




